name: Build & Deploy

on:
  pull_request:
    branches:
      - prod
    types: [closed]

jobs:
  deploy_on_mvm_ftp:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Set up make
        run: sudo apt-get install make -y

      - name: Start Docker container
        run: make start

      - name: Build Project
        run: make build

      - name: Upload /dist directory to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER_NAME }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: ${{ secrets.FTP_SERVER_PORT }}
          # Folder to upload from, must end with trailing slash /
          local-dir: ./dist/
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: ${{ secrets.FTP_DOMAIN_PATH }}
          # Prints which modifications will be made with current config options, but doesnt actually make any changes
          dry-run: true
          # Deletes ALL contents of server-dir, even items in excluded with exclude argument
          dangerous-clean-slate: true
          # How verbose should the information be - minimal, standard, or verbose
          log-level: standard
